services:
  frigate:
    container_name: Frigate_test
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://github.com/jnicolson/gasket-builder
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config:/config
      - /surveillance:/media/frigate
      - /dev/apex_0:/dev/apex_0
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8972:8971"
      - "5002:5000" # Internal unauthenticated access. Expose carefully.
      - "8552:8554" # RTSP feeds
      - "8552:8555/tcp" # WebRTC over tcp
      - "8552:8555/udp" # WebRTC over udp
